mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
]

news/urls.py
from django.urls import path

from . import views

app_name = 'news'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:headline_id>/', views.detail, name='detail'),
]

news/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Headline(models.Model):
    headline_text = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.headline_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Story(models.Model):
    headline = models.ForeignKey(Headline, on_delete=models.CASCADE)
    story_text = models.CharField(max_length=1000)
    def __str__(self):
        return self.story_text
    

news/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.http import Http404

from .models import Headline


def index(request):
    latest_headline_list = Headline.objects.order_by('-pub_date')[:5]
    template = loader.get_template('news/index.html')
    context = {
        'latest_headline_list': latest_headline_list,
    }
    return HttpResponse(template.render(context, request))

def detail(request, headline_id):
    try:
        headline = Headline.objects.get(pk=headline_id)
    except Headline.DoesNotExist:
        raise Http404("Headline does not exist")
    return render(request, 'news/detail.html', {'headline': headline})
    

news/templates/news/detail.html
{{ headline }}

<h1>{{ headline.headline_text }}</h1>
<ul>
{% for story in headline.story_set.all %}
    <li>{{ story.story_text }}</li>
{% endfor %}
</ul>

news/templates/news/index.html
{% if latest_headline_list %}
    <ul>
    {% for question in latest_headline_list %}
        <li><a href="/news/{{ headline.id }}/">{{ headline.headline_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No news is available.</p>
{% endif %}